name = "sgproxy"
main = "build/worker/shim.mjs"
compatibility_date = "2026-03-21"

[durable_objects]
bindings = [{ name = "SGPROXY_STATE", class_name = "SgproxyState" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SgproxyState"]
